// ─────────────────────────────────────────────────────────────────────────────
// Theme generator. Reads the Figma-exported token JSON and the editable
// type-styles config, then emits app/generated/theme.css:
//   • color custom properties (--color-*) from tokens/brand_colors.json
//   • font-family custom properties (--font-*)
//   • one responsive class per named type style (.type-h1, .type-r-h1, …)
//     whose font-size switches across the four breakpoints.
//
// No component hard-codes a hex or px size — they all consume this output.
// Run via `npm run generate:theme` (also wired into dev/build).
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  families,
  classPrefix,
  styles,
  breakpoints,
} from "../theme/type-styles.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const colors = JSON.parse(
  readFileSync(resolve(root, "tokens/brand_colors.json"), "utf8")
);
const typography = JSON.parse(
  readFileSync(resolve(root, "tokens/typography.json"), "utf8")
);

const kebab = (s) =>
  s
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();

// ── Colors → CSS custom properties ──────────────────────────────────────────
const colorVars = Object.entries(colors)
  .map(([name, token]) => `  --color-${kebab(name)}: ${token.value};`)
  .join("\n");

// ── Font families → CSS custom properties ───────────────────────────────────
const fontVars = Object.entries(families)
  .map(([family, stack]) => `  --font-${kebab(family)}: ${stack};`)
  .join("\n");

// ── Helpers to read a size for a family/style/breakpoint from the JSON ──────
const sizeFor = (bpKey, family, styleName) => {
  const bp = typography[bpKey];
  if (!bp || !bp[family]) return undefined;
  const entry = bp[family][styleName];
  return entry ? entry.value : undefined;
};

const declBlock = (cfg, family) => {
  const lines = [
    `  font-family: var(--font-${kebab(family)});`,
    `  font-weight: ${cfg.weight ?? 400};`,
    `  line-height: ${cfg.lineHeight ?? 1.2};`,
    `  font-style: ${cfg.italic ? "italic" : "normal"};`,
  ];
  if (cfg.letterSpacing != null)
    lines.push(`  letter-spacing: ${cfg.letterSpacing}em;`);
  if (cfg.transform) lines.push(`  text-transform: ${cfg.transform};`);
  return lines.join("\n");
};

// ── Type classes: base rule (mobile) + a media-query override per breakpoint ─
const baseRules = [];
const mediaBuckets = new Map(); // minWidth -> array of rule strings

for (const [family, familyStyles] of Object.entries(styles)) {
  const prefix = classPrefix[family];
  for (const [styleName, cfg] of Object.entries(familyStyles)) {
    const selector = `.${prefix}-${kebab(styleName)}`;

    for (const bp of breakpoints) {
      const size = sizeFor(bp.key, family, styleName);
      if (size == null) continue;

      if (bp.minWidth === 0) {
        // base (mobile): full declaration incl. size
        baseRules.push(
          `${selector} {\n${declBlock(cfg, family)}\n  font-size: ${size}px;\n}`
        );
      } else {
        // larger breakpoints: only the size needs to change
        if (!mediaBuckets.has(bp.minWidth)) mediaBuckets.set(bp.minWidth, []);
        mediaBuckets
          .get(bp.minWidth)
          .push(`  ${selector} { font-size: ${size}px; }`);
      }
    }
  }
}

const mediaBlocks = [...mediaBuckets.entries()]
  .sort((a, b) => a[0] - b[0])
  .map(
    ([minWidth, rules]) =>
      `@media (min-width: ${minWidth}px) {\n${rules.join("\n")}\n}`
  )
  .join("\n\n");

const banner =
  "/* AUTO-GENERATED by scripts/generate-theme.mjs from tokens/. Do not edit by hand. */";

const css = `${banner}

:root {
${colorVars}
${fontVars}
}

${baseRules.join("\n\n")}

${mediaBlocks}
`;

const outPath = resolve(root, "app/generated/theme.css");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css, "utf8");

const styleCount = Object.values(styles).reduce(
  (n, s) => n + Object.keys(s).length,
  0
);
console.log(
  `[generate-theme] wrote ${outPath} (${Object.keys(colors).length} colors, ${styleCount} type styles).`
);
